// WWE '13 title-update input validation. Hand-written; not generated by ReXGlue.
#pragma once

#include <filesystem>

namespace wwe13 {

enum class GameFileCheckResult {
  kSupported,
  kMissingExecutable,
  kInvalidExecutable,
  kWrongTitle,
  kMissingTitleUpdate,
  kInvalidTitleUpdate,
  kUnsupportedTitleUpdate,
  kMismatchedTitleUpdate,
};

GameFileCheckResult CheckSupportedGameFiles(const std::filesystem::path& game_directory);
void ShowUnsupportedGameFilesMessage(GameFileCheckResult result);

}  // namespace wwe13
