// WWE '13 title-update input validation. Hand-written; not generated by ReXGlue.
#include "game_version_check.h"

#include <cstdint>
#include <cstdio>
#include <fstream>
#include <limits>
#include <system_error>

namespace wwe13 {
namespace {

constexpr std::uint32_t kXex2Magic = 0x58455832;  // "XEX2"
constexpr std::uint32_t kExecutionInfoKey = 0x00040006;
constexpr std::uint32_t kDeltaPatchDescriptorKey = 0x000005FF;
constexpr std::uint32_t kWwe13TitleId = 0x545108B4;

// xex2_version in the ReXGlue/Xenia header lays out major/minor/build/qfe in
// the low-to-high bits on our little-endian x86-64 targets. 2.0.1.0 is 0x102.
constexpr std::uint32_t kWwe13TitleUpdateVersion = 0x00000102;

struct XexFile {
  std::ifstream stream;
  std::uint64_t file_size = 0;
  std::uint32_t header_size = 0;
  std::uint32_t optional_header_count = 0;
};

bool ReadBytes(XexFile& file, std::uint64_t offset, unsigned char* output,
               std::size_t count) {
  if (offset > file.file_size || count > file.file_size - offset ||
      offset > static_cast<std::uint64_t>(std::numeric_limits<std::streamoff>::max()) ||
      count > static_cast<std::size_t>(std::numeric_limits<std::streamsize>::max())) {
    return false;
  }
  file.stream.clear();
  file.stream.seekg(static_cast<std::streamoff>(offset), std::ios::beg);
  if (!file.stream) {
    return false;
  }
  file.stream.read(reinterpret_cast<char*>(output), static_cast<std::streamsize>(count));
  return file.stream.good();
}

bool ReadBigEndianU32(XexFile& file, std::uint64_t offset, std::uint32_t* output) {
  unsigned char bytes[4]{};
  if (!ReadBytes(file, offset, bytes, sizeof(bytes))) {
    return false;
  }
  *output = (static_cast<std::uint32_t>(bytes[0]) << 24) |
            (static_cast<std::uint32_t>(bytes[1]) << 16) |
            (static_cast<std::uint32_t>(bytes[2]) << 8) |
            static_cast<std::uint32_t>(bytes[3]);
  return true;
}

bool OpenXex2(const std::filesystem::path& path, XexFile* file) {
  std::error_code error;
  file->file_size = std::filesystem::file_size(path, error);
  if (error || file->file_size < 0x18) {
    return false;
  }
  file->stream.open(path, std::ios::binary);
  if (!file->stream) {
    return false;
  }

  std::uint32_t magic = 0;
  if (!ReadBigEndianU32(*file, 0, &magic) || magic != kXex2Magic ||
      !ReadBigEndianU32(*file, 8, &file->header_size) ||
      !ReadBigEndianU32(*file, 0x14, &file->optional_header_count)) {
    return false;
  }
  if (file->header_size < 0x18 || file->header_size > file->file_size ||
      file->optional_header_count > (file->header_size - 0x18) / 8) {
    return false;
  }
  return true;
}

bool FindOptionalHeaderOffset(XexFile& file, std::uint32_t key, std::uint32_t* offset) {
  bool found = false;
  for (std::uint32_t i = 0; i < file.optional_header_count; ++i) {
    const std::uint64_t entry = 0x18 + static_cast<std::uint64_t>(i) * 8;
    std::uint32_t current_key = 0;
    std::uint32_t current_value = 0;
    if (!ReadBigEndianU32(file, entry, &current_key) ||
        !ReadBigEndianU32(file, entry + 4, &current_value)) {
      return false;
    }
    if (current_key != key) {
      continue;
    }
    if (found || current_value > file.header_size) {
      return false;
    }
    *offset = current_value;
    found = true;
  }
  return found;
}

bool ReadExecutionInfo(XexFile& file, std::uint32_t* version, std::uint32_t* base_version,
                       std::uint32_t* title_id) {
  std::uint32_t offset = 0;
  if (!FindOptionalHeaderOffset(file, kExecutionInfoKey, &offset) ||
      offset > file.header_size || file.header_size - offset < 0x18 ||
      !ReadBigEndianU32(file, offset + 4, version) ||
      !ReadBigEndianU32(file, offset + 8, base_version) ||
      !ReadBigEndianU32(file, offset + 0xC, title_id)) {
    return false;
  }
  return true;
}

bool ReadDeltaPatchVersions(XexFile& file, std::uint32_t* source_version,
                            std::uint32_t* target_version) {
  std::uint32_t offset = 0;
  std::uint32_t descriptor_size = 0;
  if (!FindOptionalHeaderOffset(file, kDeltaPatchDescriptorKey, &offset) ||
      offset > file.header_size || file.header_size - offset < 0x4C ||
      !ReadBigEndianU32(file, offset, &descriptor_size) || descriptor_size < 0x4C ||
      descriptor_size > file.header_size - offset ||
      !ReadBigEndianU32(file, offset + 4, target_version) ||
      !ReadBigEndianU32(file, offset + 8, source_version)) {
    return false;
  }
  return true;
}

}  // namespace

GameFileCheckResult CheckSupportedGameFiles(const std::filesystem::path& game_directory) {
  const auto executable_path = game_directory / "default.xex";
  const auto update_path = game_directory / "default.xexp";

  std::error_code error;
  if (!std::filesystem::is_regular_file(executable_path, error)) {
    return GameFileCheckResult::kMissingExecutable;
  }
  error.clear();
  if (!std::filesystem::is_regular_file(update_path, error)) {
    return GameFileCheckResult::kMissingTitleUpdate;
  }

  XexFile executable;
  if (!OpenXex2(executable_path, &executable)) {
    return GameFileCheckResult::kInvalidExecutable;
  }

  std::uint32_t executable_version = 0;
  std::uint32_t executable_base_version = 0;
  std::uint32_t title_id = 0;
  if (!ReadExecutionInfo(executable, &executable_version, &executable_base_version, &title_id)) {
    return GameFileCheckResult::kInvalidExecutable;
  }
  if (title_id != kWwe13TitleId) {
    return GameFileCheckResult::kWrongTitle;
  }

  XexFile update;
  if (!OpenXex2(update_path, &update)) {
    return GameFileCheckResult::kInvalidTitleUpdate;
  }

  std::uint32_t source_version = 0;
  std::uint32_t target_version = 0;
  if (!ReadDeltaPatchVersions(update, &source_version, &target_version)) {
    return GameFileCheckResult::kInvalidTitleUpdate;
  }
  if (target_version != kWwe13TitleUpdateVersion) {
    return GameFileCheckResult::kUnsupportedTitleUpdate;
  }
  if (source_version != executable_version && source_version != executable_base_version) {
    return GameFileCheckResult::kMismatchedTitleUpdate;
  }

  return GameFileCheckResult::kSupported;
}

void ShowUnsupportedGameFilesMessage(GameFileCheckResult result) {
  (void)result;
  std::fputs("WWE '13 requires a matching title update 2.0.1.0 game folder with "
             "default.xex and default.xexp.\n",
             stderr);
}

}  // namespace wwe13
