#!/usr/bin/env python3
"""Generate a compressed, embedded ImGui font-data header in the build directory."""

import pathlib
import subprocess
import sys


def main() -> int:
    if len(sys.argv) != 4:
        raise SystemExit("usage: generate_fonts.py COMPRESSOR FONT_DIR OUTPUT_HEADER")
    compressor = sys.argv[1]
    font_dir = pathlib.Path(sys.argv[2])
    output = pathlib.Path(sys.argv[3])
    faces = (
        ("Oswald-Medium.ttf", "OswaldMedium"),
        ("Oswald-SemiBold.ttf", "OswaldSemiBold"),
        ("Oswald-Bold.ttf", "OswaldBold"),
        ("Barlow-Regular.ttf", "BarlowRegular"),
        ("Barlow-Medium.ttf", "BarlowMedium"),
        ("Barlow-SemiBold.ttf", "BarlowSemiBold"),
        ("NotoSans-Variable.ttf", "NotoSans"),
        ("NotoSansSymbols2-Regular.ttf", "NotoSansSymbols2"),
    )
    chunks = ["// Generated by ui/generate_fonts.py; do not edit.\n"]
    for filename, symbol in faces:
        source = font_dir / filename
        generated = subprocess.run(
            [compressor, "-u8", str(source), symbol],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        chunks.append(generated.stdout)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(chunks), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
